### ISSUE TITLE
Command MLRtimesetup is unrecognized

### ISSUE THREAD

**Issue by ledwindra** [NickCH-K/MLRtime#1]
Hi @NickCH-K,

First of all, thanks so much for creating this package. I got a minor issue when running this package

# Details

1. Operating system. Both the OS and Stata were freshly installed to avoid dependencies issues as I used a Docker image that I've [created](https://github.com/ledwindra/docker-stata)

```
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

2. Stata version

```stata
. version
version 15.1
```

3. I have R installed and it's callable from the command line as you specified when I invoked `help MLRtimesetup`

```
R must be installed first before running MLRtimesetup, and R must be
    callable from the command line
```

![image](https://user-images.githubusercontent.com/39021609/136944183-61d359d8-9091-4d78-8b41-5e8dd7885745.png)

4. However, when I executed the `MLRtimesetup` command itself, it produced

```
. MLRtimesetup
command MLRtimesetup is unrecognized
r(199);
```

5. So I installed both `github` and `rcall` manually, which worked

```
. ado

[1] package MLRtime from https://raw.githubusercontent.com/NickCH-K/MLRtime/master
      'MLRtime': Machine Learning in R... in Stata

[2] package github from https://haghish.github.io/github
      'GITHUB': github package manager

[3] package rcall from /home/notebook/rcall-3.1.0
      'RCALL': seamless R in Stata
```

# Question
Having said this, did I do something wrong so that `MLRtimesetup` command doesn't work in me?

Some potential users might find it quite tedious to manually install both Stata packages (`github` and `rcall`) and R packages (`broom`, `broom.mixed`, etc), especially if they're not familiar with command line (as mentioned, users need to be able to invoke R through it)

Thanks again! 🙌🏽

**Comment by NickCH-K** [comment]
Hmm, shoot, that's no good! I'm wondering if rcall can't find your R installation. Does rcall on its own work? Try

rcall: a = 1

If that throws an error, then it's having trouble finding your R installation and that's the problem. If not, then my R-detection code is faulty.

On Oct 12, 2021 4:15 AM, Lukman Edwindra ***@***.***> wrote:

Hi @NickCH-K<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNickCH-K&data=04%7C01%7Cnhuntington-klein%40seattleu.edu%7C9f1b7dd9a23a450cab5c08d98d718940%7Cbc10e052b01c48499967ee7ec74fc9d8%7C0%7C0%7C637696341071153419%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Lxnq8JDr6P6pGbAh20QqOWBEnmJ5DH4aOHTPU305D6Q%3D&reserved=0>,

First of all, thanks so much for creating this package. I got a minor issue that when running this package

Details

  1.  Operating system. Both the OS and Stata were freshly installed to avoid dependencies issues as I used a Docker image that I've created<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fledwindra%2Fdocker-stata&data=04%7C01%7Cnhuntington-klein%40seattleu.edu%7C9f1b7dd9a23a450cab5c08d98d718940%7Cbc10e052b01c48499967ee7ec74fc9d8%7C0%7C0%7C637696341071163412%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=87ZANI3ZTwgyvOZHWlby%2F6lDhUc16tbu%2Fq37Ax7gkCc%3D&reserved=0>

NAME="Ubuntu"

VERSION="20.04.3 LTS (Focal Fossa)"

ID=ubuntu

ID_LIKE=debian

PRETTY_NAME="Ubuntu 20.04.3 LTS"

VERSION_ID="20.04"

HOME_URL="https://www.ubuntu.com/"

SUPPORT_URL="https://help.ubuntu.com/"

BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"

PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"

VERSION_CODENAME=focal

UBUNTU_CODENAME=focal



  1.  Stata version

. version

version 15.1

  1.  I have R installed and it's callable from the command line as you specified when I invoked help MLRtimesetup

R must be installed first before running MLRtimesetup, and R must be

    callable from the command line



[image]<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F39021609%2F136944183-61d359d8-9091-4d78-8b41-5e8dd7885745.png&data=04%7C01%7Cnhuntington-klein%40seattleu.edu%7C9f1b7dd9a23a450cab5c08d98d718940%7Cbc10e052b01c48499967ee7ec74fc9d8%7C0%7C0%7C637696341071173416%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=CJwX64LG1THz%2FlZJQqoGaxNioDwaC7Ir0W%2FRYuh%2FC%2FQ%3D&reserved=0>

  1.  However, when I executed the MLRtimesetup command itself, it produced

. MLRtimesetup

command MLRtimesetup is unrecognized

r(199);



  1.  So I installed both github and rcall manually, which worked

. ado



[1] package MLRtime from https://raw.githubusercontent.com/NickCH-K/MLRtime/master

      'MLRtime': Machine Learning in R... in Stata



[2] package github from https://haghish.github.io/github

      'GITHUB': github package manager



[3] package rcall from /home/notebook/rcall-3.1.0

      'RCALL': seamless R in Stata



Question

Having said this, did I do something wrong so that MLRtimesetup command doesn't work in me?

Some potential users might find it quite tedious to manually install both Stata packages (github and rcall) and R packages (broom, broom.mixed, etc), especially if they're not familiar with command line (as mentioned, users need to be able to invoke R through it)

Thanks again! 🙌🏽

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNickCH-K%2FMLRtime%2Fissues%2F1&data=04%7C01%7Cnhuntington-klein%40seattleu.edu%7C9f1b7dd9a23a450cab5c08d98d718940%7Cbc10e052b01c48499967ee7ec74fc9d8%7C0%7C0%7C637696341071173416%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2FxgtliSvvDZXWWzfwIXx1f5oMWXvDHzWCrKkliGAG4Q%3D&reserved=0>, or unsubscribe<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAKV5TDOBR3MCRXPQQLYO3QTUGQKDFANCNFSM5F2J7SOQ&data=04%7C01%7Cnhuntington-klein%40seattleu.edu%7C9f1b7dd9a23a450cab5c08d98d718940%7Cbc10e052b01c48499967ee7ec74fc9d8%7C0%7C0%7C637696341071173416%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=bcg4dBc9B8Zogcql6TzAOqcrX006Gu7Pxn7OuXnzd5M%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cnhuntington-klein%40seattleu.edu%7C9f1b7dd9a23a450cab5c08d98d718940%7Cbc10e052b01c48499967ee7ec74fc9d8%7C0%7C0%7C637696341071183399%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=vgJnra1nL75qeS6kIrAS2l%2FA25gl8L3DJkUxBKRSl1Y%3D&reserved=0> or Android<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cnhuntington-klein%40seattleu.edu%7C9f1b7dd9a23a450cab5c08d98d718940%7Cbc10e052b01c48499967ee7ec74fc9d8%7C0%7C0%7C637696341071183399%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=7Q4OGRvObZpWUp5itbrL4UB6AeI1kBhI2VNN9PXTvFI%3D&reserved=0>.

**Comment by ledwindra** [comment]
`rcall` works fine after I manually installed it. In fact, I was able to execute your example (e.g. `grf` command) Here's the result of your example:

```
. rcall: a = 1

. rcall: a
[1] 1
```

My R is located at `/usr/bin/R`, which is the default location both on Mac and Linux, at least as specified on `rcall.ado` [source code](https://github.com/haghish/rcall/blob/10ceed4178733b9c17b4bb3a2a0393f5febf66b3/rcall.ado#L466)

```stata
 				// for linux and Mac try 2 possible default paths
			else {
				local path "/usr/bin/R"
				capture confirm file "`path'"
				if _rc != 0 {
					local path "/usr/local/bin/R"
					global Rpath : display "`path'"
				}
```

**Comment by ledwindra** [comment]
After figuring out further, it seems that your program works fine. I copied and pasted your `MLRtimesetup.ado` to my Stata console and when I invoked `MLRtimesetup` it successfully installed all packages with following end result:

```
There were 8 unique warnings (type 'rcall warnings' to see them)
You're good to go! Everything is installed.
You may want to rerun MLRtimesetup regularly to get updated versions of packages.
```

Maybe the issue is on my side (operating system or Docker configuration, I'm not sure). So, to save your time, I'm closing this issue. Thanks so much! 🙌🏽
